//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmCentralRedo3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string employeeID { get; set; }
        public string employeeName { get; set; }
        public string employeeSurname { get; set; }
        public string employeeEmail { get; set; }
        public string employeePassword { get; set; }
    }
}
