//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmCentralRedo3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer
    {
        public string farmerID { get; set; }
        public string farmerName { get; set; }
        public string farmerLocation { get; set; }
        public int farmerNumber { get; set; }
        public string farmerEmail { get; set; }
        public string farmerPassword { get; set; }
    }
}
